# In Floodgate bedrock player data is send encrypted
# The following value should point to the key Floodgate generated.
# The public key should be used for the Geyser(s) and the private key for the Floodgate(s)
key-file-name: key.pem

# Floodgate prepends a prefix to bedrock usernames to avoid conflicts
# However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
# It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
username-prefix: "*"

# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true

# Should Floodgate apply the transferred Bedrock to Java skin directly to all Java players?
# This might cause some
apply-skin-directly: true

# The default locale for Floodgate. By default, Floodgate uses the system locale
# default-locale: en_US

disconnect:
  # The disconnect message Geyser users should get when connecting
  # to the server with an invalid key
  invalid-key: Please connect through the official Geyser
  # The disconnect message Geyser users should get when connecting
  # to the server with the correct key but not with the correct data format
  invalid-arguments-length: Expected {} arguments, got {}. Is Geyser up-to-date?

# Configuration for player linking
player-link:
  # Whether to enable the linking system. Turning this off will prevent
  # players from using the linking feature even if they are already linked.
  enabled: false
  # Whether to allow the use of /linkaccount and /unlinkaccount
  # You can also use allow specific people to use the commands using the
  # permissions floodgate.linkaccount and floodgate.unlinkaccount.
  # This is only for linking, already connected people will stay connected
  allowed: true
  # The amount of time until a link code expires in seconds
  link-code-timeout: 300
  database:
    # The database type you want to use.
    # The option is only used when auto-download is enabled or when
    # there are more then one database implementations found in the config directory
    # current options: sqlite, mariadb
    type: sqlite
    # These settings are not used for sqlite, but are for others (like mariadb)
    database: floodgate
    username: floodgate
    password: P4ssw0rd
    hostname: localhost
    # Automatically download the database type you want to use
    # Note that this doesn't include auto-update (database implementations don't have to be updated frequently)
    auto-download: true

# Do not change this
config-version: 1
